# note: currently jwilder/nginx-proxy does not work with docker-compose v2 configuration
# https://github.com/jwilder/nginx-proxy#docker-compose
version: "2"
services:
  consul:
    command: -server -bootstrap -client 0.0.0.0 -ui-dir /ui
    image: progrium/consul
    expose:
      - "8300"
      - "8400"
      - "8500"
      - "8600/tcp"
      - "8600/udp"
    environment:
      - "affinity:container!=nodes_consul_*"
      - GOMAXPROCS=2
  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500 -ip 127.0.0.1
    hostname: default
    container_name: registrator
    depends_on:
      - consul
    environment:
      - "affinity:container!=nodes_registrator_*"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./legacy/src/main/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - front
    environment:
      - DEFAULT_HOST=front.service.consul
  front:
    build: legacy
    depends_on:
      - consul
      - file_storage
    dns_search: ''
    expose:
      - "8080"
      - "5701"
      - "54327/udp"
    environment:
      - VIRTUAL_HOST=front.service.consul
      - VIRTUAL_PORT=8080
  file_storage:
    build: file-storage
    volumes:
      - storage:/mnt/brownie
    dns_search: ''
    depends_on:
      - consul
      - file_storage_db
    expose:
      - "8080"
      - "5701"
      - "54327/udp"
  file_storage_db:
    image: postgres:9
    environment:
      - POSTGRES_USER=brownie
      - POSTGRES_PASSWORD=brownie
      - POSTGRES_DB=brownie
    expose:
      - "5432"
    ports:
      - "25432:5432" # for JUnit
    depends_on:
      - consul
    volumes:
      - ./file-storage/src/main/sql:/docker-entrypoint-initdb.d
  encoder:
    build: encoder
    dns_search: ''
    depends_on:
      - consul
      - file_storage
    expose:
      - "8080"
      - "5701"
      - "54327/udp"
  thumbnail:
    build: thumbnail
    dns_search: ''
    depends_on:
      - consul
      - file_storage
      - thumbnail_db
    expose:
      - "8080"
      - "5701"
      - "54327/udp"
  thumbnail_db:
    image: postgres:9
    environment:
      - POSTGRES_USER=brownie
      - POSTGRES_PASSWORD=brownie
      - POSTGRES_DB=brownie
    expose:
      - "5432"
    ports:
      - "35432:5432" # for JUnit
    depends_on:
      - consul
    volumes:
      - ./thumbnail/src/main/sql:/docker-entrypoint-initdb.d
volumes:
  storage:
    external: false
